### ISSUE TITLE
wget returning 404 on valid requests in python3

### ISSUE THREAD

**Issue by murt** [Lecrapouille/gdcef#1]
For _whatever_ reason the much more common "wget" module for python is returning 404s when attempting to download the cef binaries even though the URLs are definitely correct.

It may be worth noting in the `README`, as per this [Stack Overflow Question](https://stackoverflow.com/questions/44828446/http-error-404-not-found-when-using-wget-to-download-a-link), using "python3-wget" resolves the issue without having to change anything in the `build.py`

**Comment by Lecrapouille** [comment]
@murt Thank to you I just realized that I forgot to copy prerequisite section from the original project:
https://github.com/stigmee/install#step-2-install-python3-packages

**Comment by Lecrapouille** [comment]
@murt Ok I fixed the doc. Please re-open the ticket if this documentation is still unclear.

**Comment by raphipod** [comment]
Installed the recommended package "wget" instead of "python3-wget" as stated in the README, still getting this error.

`urllib.error.HTTPError: HTTP Error 404: Not Found`

File link downloads fine through the webbrowser.

**Comment by raphipod** [comment]
Turns out that URL percent encoding is causing the issue. I'm going to open a PR with the fix, and while I am at it, I'll update the CEF version, too.

**Comment by Lecrapouille** [comment]
@raphipod I tried quickly: I uninstalled python3-wget and installed back wget and the `+` seems working but not the `%2B` (by the way, when you copy the URL from your browser you have `%2B`). At the opposite, from my memory, python3-wget does not like `+` but prefer `%2B`, and both uses `import wget` and requirements.txt generates wget for python3-wget :( :(

**Comment by Lecrapouille** [comment]
> Concerning the URL encoding issues, I really don't know why it fails at my end

I think this is a mix up between python3_wget and wget while using `import wget`

**Comment by raphipod** [comment]
Yeah, we should use python3-wget, already corrected that in PR#2

**Comment by Lecrapouille** [comment]
@raphipod @murt I have radically changed of package for downloading :) no more wget. I added the requierement file and updated README. I also updated CEF version. I hardly checked. Tell me if this is ok for you. If ok @raphipod you can cancel your PR

**Comment by raphipod** [comment]
I just noticed that you've commented out the colon in line 346, it exits.

**Comment by raphipod** [comment]
All right, it downloads now without errors! If @murt can confirm that too.
